# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


'''
list(a): convert to list of arrays
a.tolist(): convert to list of lists
'''

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [2]:
# 記得先 Import 正確的套件

import numpy as np

In [3]:

a = np.random.randint(10, size=6) 

print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[8 1 5 1 9 9]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [4]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[5 7 4 8]
 [7 6 7 4]
 [5 6 3 1]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [5]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[8 5]
  [7 1]
  [9 9]]

 [[1 7]
  [9 8]
  [2 2]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [6]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[6, 8, 9, 8, 7, 0]
[6, 8, 9, 8, 7, 0]


In [7]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[3, 1, 6, 4], [0, 8, 9, 4], [3, 4, 6, 4]]
[array([3, 1, 6, 4]), array([0, 8, 9, 4]), array([3, 4, 6, 4])]


In [8]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[6, 0], [2, 1], [1, 4]], [[4, 2], [8, 4], [7, 9]]]
[array([[6, 0],
       [2, 1],
       [1, 4]]), array([[4, 2],
       [8, 4],
       [7, 9]])]


In [9]:
def tolist(iterable):
    list_result = []
    if iterable.ndim == 1:
        return list(iterable)
    else:
        for row in iterable:
            list_result.append(tolist(row))
    return list_result

print(tolist(a))
print(tolist(b))
print(tolist(c))

[6, 8, 9, 8, 7, 0]
[[3, 1, 6, 4], [0, 8, 9, 4], [3, 4, 6, 4]]
[[[6, 0], [2, 1], [1, 4]], [[4, 2], [8, 4], [7, 9]]]


作業目標:<br>
在array中，可以靈活應用索引幫助資料擷取<br>
作業重點:<br>
陣列的索引、切片、以及屬性，皆需要注意使用方式<br>
陣列之中索引式由0開始請同學注意

題目:<br>
1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。<br>
2.呈上題，將以上數列取出偶數。<br>
3.呈1題，將數列取出3的倍數。<br>

In [11]:
import numpy as np

In [12]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
def arithmetic_sequence(_start, _end, _step, endpoint):
    start = _start
    end = _end
    if endpoint:
        end += _step
    return np.arange(start, end, _step)

q1 = arithmetic_sequence(0, 20, 1, True)
print(q1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [13]:
#2.呈上題，將以上數列取出偶數。
q2 = [item for item in q1 if item % 2 == 0]
print(q2)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [14]:
#3.呈1題，將數列取出3的倍數。
q3 = [item for item in q1 if item % 3 == 0]
print(q3)

[0, 3, 6, 9, 12, 15, 18]
