# [作業目標]

1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

```
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
```

2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式

3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？

```
def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)
```

# 作業 

### 1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

```
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
```


```
type()用於獲取資料型別
dtype用於獲取陣列中元素的型別
```

### 2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式，並且通過測試。



In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [2]:
def is_dtype(_a, _t):
    return _a.dtype == _t


In [3]:
a = np.random.randint(10, size=6) 

# 測試一
print(is_dtype(a, 'int')) # True

# 測試二
print(is_dtype(a, np.int)) # True

# 測試三
print(is_dtype(a, np.dtype('int'))) # True

True
True
True


### 3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？

```
def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)
```

```
== 是判斷兩個變數之間的『值』是否相同
is 是判斷兩個變數之間的『記憶體位址』是否相同

type()用於獲取資料型別
dtype用於獲取陣列中元素的型別
```

作業目標<br>
熟悉陣列維度轉換，並且會擷取需要資料<br>
作業重點<br>
使用reshap須注意order用法<br>
where可以運用邏輯條件擷取資料

題目:<br>
1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")<br>
2.呈上題的array，找出被6除餘1的數的索引<br>

In [6]:
import numpy as np

In [7]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
print(array1)
array1 = array1.reshape((5, 6), order='F')
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [8]:
#2.呈上題的array，找出被6除餘1的數的索引
array2 = np.where(array1 % 6 == 1)
print(array2)

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))
